theme:
  name: material
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Light mode (to enable this when the feature is released)
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
site_name: <$name> Package Documentation
site_url: https://www.github.com
nav:
  - Home: index.md
  - About this package: 
      - 'Purpose': 'about/about_this_package.md' 
  - Getting Started: 
      - 'How to use this package ?': 'getting-started/getting_started.md'
      