# Package info section
name: <$name>
description: This is the <$name> package implementation
url: <$url>
version: 0.1

# Package variants section

variants:     
            
    variant_1:
        platform:
            - clang

# Doc section

#doc:

# Tests section

#tests:

# Metrics section

#metrics:

# Tools section

#tools:
#core_tools:
#clang:

#other_tools:
#report_generator:
